/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wobiancao_ndkjnidemo_ndk_JniUtils */

#ifndef _Included_com_wobiancao_ndkjnidemo_ndk_JniUtils
#define _Included_com_wobiancao_ndkjnidemo_ndk_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wobiancao_ndkjnidemo_ndk_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wobiancao_ndkjnidemo_ndk_JniUtils_getStringFormC
  (JNIEnv *, jclass);

/*
 * Class:     com_wobiancao_ndkjnidemo_ndk_JniUtils
 * Method:    getKeyValue
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wobiancao_ndkjnidemo_ndk_JniUtils_getKeyValue
  (JNIEnv *, jclass);

/*
 * Class:     com_wobiancao_ndkjnidemo_ndk_JniUtils
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wobiancao_ndkjnidemo_ndk_JniUtils_getIv
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
